import{a as $,S as k,i as y}from"./assets/vendor-DtRopbQG.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const s of r.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&a(s)}).observe(document,{childList:!0,subtree:!0});function n(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function a(e){if(e.ep)return;e.ep=!0;const r=n(e);fetch(e.href,r)}})();const C="49317113-6ec0477c2a8a63e568c804eb9",N="https://pixabay.com/api/";async function g(t,o=1){var n,a;try{const e=await $.get(N,{params:{key:C,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,page:o,per_page:15}});if(e.data.hits.length===0)throw new Error("No images found");return{images:e.data.hits,totalHits:e.data.totalHits}}catch(e){throw new Error(((a=(n=e.response)==null?void 0:n.data)==null?void 0:a.message)||e.message)}}const f=document.querySelector(".gallery"),p=document.querySelector(".loader"),h=document.querySelector(".load-more"),b=document.querySelector(".end-message"),O=new k(".gallery a",{captionsData:"alt",captionDelay:250});function L(){p.style.display="block"}function w(){p.style.display="none"}function S(){h.style.display="block"}function u(){h.style.display="none"}function x(){b.style.display="block"}function q(){b.style.display="none"}function E(t,o=!1){const n=t.map(({webformatURL:a,largeImageURL:e,tags:r,likes:s,views:B,comments:H,downloads:P})=>`
      <li class="gallery-item">
        <a href="${e}">
          <img src="${a}" alt="${r}" />
        </a>
        <div class="info">
          <p><b>Likes</b> ${s}</p>
          <p><b>Views</b> ${B}</p>
          <p><b>Comments</b> ${H}</p>
          <p><b>Downloads</b> ${P}</p>
        </div>
      </li>`).join("");o?f.insertAdjacentHTML("beforeend",n):f.innerHTML=n,O.refresh()}function T(){var o;const{height:t}=((o=document.querySelector(".gallery-item"))==null?void 0:o.getBoundingClientRect())||{height:0};window.scrollBy({top:t*2,behavior:"smooth"})}const A=document.querySelector(".form"),l=document.querySelector('input[name="search-text"]'),D=document.querySelector(".gallery");let i=1,c="",d=0;A.addEventListener("submit",async t=>{if(t.preventDefault(),c=l.value.trim(),!c){R("Please enter a search term!");return}i=1,u(),q(),D.innerHTML="",L();try{const{images:o,totalHits:n}=await g(c,i);d=n,E(o),M(o.length,d)}catch(o){v(o)}finally{w()}});document.querySelector(".load-more").addEventListener("click",async()=>{L(),u(),i+=1;try{const{images:t}=await g(c,i);E(t,!0),T(),M(t.length,d)}catch(t){v(t),S()}finally{w()}});function M(t,o){i*15>=o?(u(),x()):(S(),q())}function v(t){t.message==="No images found"?m("Sorry, there are no images matching your search query. Please try again!"):m(t.message),l.classList.add("error"),setTimeout(()=>l.classList.remove("error"),1e3)}function R(t){y.warning({title:"Warning",message:t,position:"topRight",backgroundColor:"#ffc107",theme:"dark",progressBarColor:"#ffd54f",timeout:3e3})}function m(t){y.error({title:"Error",message:t,position:"topRight",backgroundColor:"#ff4444",theme:"dark",progressBarColor:"#ff6666",timeout:5e3,displayMode:2,layout:2})}
//# sourceMappingURL=index.js.map
